### ISSUE TITLE
Artículo con varios atributos iguales

### ISSUE THREAD

**Issue by JohnnyVM** [Comunitea/CMNT_00146_2018_ANZ#20]
Cuando tengo un producto con varios valores de atributo con el mismo nombre (pasa, no debería pero eso es otro tema) falla y no se agrega al carrito
El error salta aquí, (odoo por defecto controla el caso aceptablemente):

https://github.com/Comunitea/CMNT_00146_2018_ANZ/blob/master/project-addons/website_base_multi_anz/controllers/website.py linea 60
attr_name = product_id.attribute_value_ids.sudo().search([('id', '=', int(key, 10))], limit=1).name

Ejemplo: https://pointsport.es/product/calcetin-pack-3-7312-200-18365

**Comment by omar7r** [comment]
Hola Juan,

Es normal que falle, Odoo no esperar que una variante se repita con los mismo atributos, no debería de ser posible, seguramente este caso se dio en la importación, ahora habría que corregirlo en la bbdd, me imagino que ponerle el atributo correcto a una de las variante con atributo duplicado porque veo que tienen un código distinto, así que no debe ser el atributo correcto, luego hay un cuarto producto generado por Odoo que habría que deactivar supongo.

**Comment by JohnnyVM** [comment]
Ok, le daré una vuelta, en el mejor de los casos con el "arreglar variantes" de kiko deberá ser suficiente, si nó habrá que hacerlos desaparecer tras un ajuste de inventario
